spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/cashflow
  rabbitmq:
    addresses: amqp://guest:guest@localhost:5672
ledger:
  base-url: http://localhost:8081
server:
  port: 8081
logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunction: TRACE